services:
 mariadb:
  container_name: mariadb
  networks:
   - inception
  build:
   context: ./requirements/mariadb
   dockerfile: Dockerfile
  env_file: .env
  volumes:
   - mariadb_v:/var/lib/mysql
  restart: unless-stopped
  expose:
   - "3306"

 wordpress:
  container_name: wordpress
  networks:
   - inception
  build:
   context: ./requirements/wordpress
   dockerfile: Dockerfile
  env_file: .env
  volumes:
   - wordpress_v:/var/www/html
  restart: on-failure
  depends_on: 
   - mariadb
  expose:
   - "9000"

 nginx:
  container_name: nginx
  networks:
   - inception
  build:
   context: ./requirements/nginx
   dockerfile: Dockerfile
  env_file: .env
  volumes:
   - wordpress_v:/var/www/html
  restart: on-failure
  depends_on:
   - wordpress
  ports:
   - "443:443"

volumes:
 wordpress_v:
  driver: local
  driver_opts:
   type: none
   device: /home/davda-si/login/data/wp
   o: bind
 mariadb_v:
  driver: local
  driver_opts:
   type: none
   device: /home/davda-si/login/data/mdb
   o: bind

networks:
 inception:
  driver: bridge